make
Former-commit-id: 418c611a039c2825df5a92d2b7c6adb7216ed50e

diff --git a/libs/Makefile b/libs/Makefile
--- a/libs/Makefile
+++ b/libs/Makefile
@@ -6,10 +6,11 @@ all :
 	  if $(MAKE) -C $$d all ; then \
 	    tar -C $$d --exclude='.*' -cf - lib include | tar xf - ; \
 	  else \
+	    echo "error making $$d"; \
 	    ok=0; \
 	  fi; \
 	done; \
-	exit $$((!$ok))
+	if [ "$$ok" = "0" ] ; then exit 1 ; fi
 
 clean :
 	for d in $(DIRS); do $(MAKE) -C $$d clean; done
